[2024-12-17T13:38:56.678+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: arsenal_mancity_player_to_postgres.process_arsenal_player manual__2024-12-17T13:38:53.225468+00:00 [queued]>
[2024-12-17T13:38:56.684+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: arsenal_mancity_player_to_postgres.process_arsenal_player manual__2024-12-17T13:38:53.225468+00:00 [queued]>
[2024-12-17T13:38:56.684+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-17T13:38:56.700+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_arsenal_player> on 2024-12-17 13:38:53.225468+00:00
[2024-12-17T13:38:56.704+0000] {standard_task_runner.py:57} INFO - Started process 27309 to run task
[2024-12-17T13:38:56.711+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'arsenal_mancity_player_to_postgres', 'process_arsenal_player', 'manual__2024-12-17T13:38:53.225468+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/arsenal_mancity_player_to_postgres.py', '--cfg-path', '/tmp/tmpue_dnp_q']
[2024-12-17T13:38:56.718+0000] {standard_task_runner.py:85} INFO - Job 389: Subtask process_arsenal_player
[2024-12-17T13:38:56.764+0000] {task_command.py:410} INFO - Running <TaskInstance: arsenal_mancity_player_to_postgres.process_arsenal_player manual__2024-12-17T13:38:53.225468+00:00 [running]> on host 653f470dc9b4
[2024-12-17T13:38:56.868+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='arsenal_mancity_player_to_postgres' AIRFLOW_CTX_TASK_ID='process_arsenal_player' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T13:38:53.225468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T13:38:53.225468+00:00'
[2024-12-17T13:38:56.871+0000] {logging_mixin.py:149} INFO - Downloading 'arsenal_player.json' from bucket 'arsenal-data'...
[2024-12-17T13:38:57.029+0000] {logging_mixin.py:149} INFO - File 'arsenal_player.json' successfully downloaded to '/tmp/arsenal_player.json'.
[2024-12-17T13:38:57.030+0000] {logging_mixin.py:149} INFO - Loading data from 'arsenal_player.json' into PostgreSQL...
[2024-12-17T13:38:57.031+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/arsenal_mancity_player_to_postgres.py", line 115, in download_and_load
    load_json_to_postgres(file_name)
  File "/opt/airflow/dags/arsenal_mancity_player_to_postgres.py", line 74, in load_json_to_postgres
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***" (172.29.0.6), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-17T13:38:57.041+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=arsenal_mancity_player_to_postgres, task_id=process_arsenal_player, execution_date=20241217T133853, start_date=20241217T133856, end_date=20241217T133857
[2024-12-17T13:38:57.061+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 389 for task process_arsenal_player (connection to server at "***" (172.29.0.6), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 27309)
[2024-12-17T13:38:57.096+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-17T13:38:57.115+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
