[2024-12-13T21:37:52.957+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_playerstats manual__2024-12-13T21:37:51.104851+00:00 [queued]>
[2024-12-13T21:37:52.971+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_playerstats manual__2024-12-13T21:37:51.104851+00:00 [queued]>
[2024-12-13T21:37:52.974+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-13T21:37:53.018+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transfer_playerstats> on 2024-12-13 21:37:51.104851+00:00
[2024-12-13T21:37:53.030+0000] {standard_task_runner.py:57} INFO - Started process 59288 to run task
[2024-12-13T21:37:53.039+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_premierleague_to_analisis', 'transfer_playerstats', 'manual__2024-12-13T21:37:51.104851+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/etl_premierleague_to_analisis.py', '--cfg-path', '/tmp/tmp8ctqg39j']
[2024-12-13T21:37:53.061+0000] {standard_task_runner.py:85} INFO - Job 190: Subtask transfer_playerstats
[2024-12-13T21:37:53.182+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_premierleague_to_analisis.transfer_playerstats manual__2024-12-13T21:37:51.104851+00:00 [running]> on host 653f470dc9b4
[2024-12-13T21:37:53.386+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_premierleague_to_analisis' AIRFLOW_CTX_TASK_ID='transfer_playerstats' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T21:37:51.104851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T21:37:51.104851+00:00'
[2024-12-13T21:37:53.410+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T21:37:53.484+0000] {sql.py:375} INFO - Running statement: SELECT player_stat_id, match_id, player_id, minutes_played, goals, assists, shots, shots_on_target, tackles, interceptions, passes_completed, xg, xa FROM premierleague.public.player_stats_source, parameters: None
[2024-12-13T21:37:53.488+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_premierleague_to_analisis.py", line 22, in transfer_table_in_same_connection
    source_data = db_hook.get_records(source_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "public.player_stats_source" does not exist
LINE 1: ...les, interceptions, passes_completed, xg, xa FROM premierlea...
                                                             ^

[2024-12-13T21:37:53.517+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_premierleague_to_analisis, task_id=transfer_playerstats, execution_date=20241213T213751, start_date=20241213T213752, end_date=20241213T213753
[2024-12-13T21:37:53.552+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 190 for task transfer_playerstats (relation "public.player_stats_source" does not exist
LINE 1: ...les, interceptions, passes_completed, xg, xa FROM premierlea...
                                                             ^
; 59288)
[2024-12-13T21:37:53.604+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T21:37:53.707+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
